name: dstu_helper
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  firebase_core: ^1.13.1
  equatable: ^2.0.3
  cloud_firestore: ^3.1.11
  flutterfire_ui: ^0.3.6
  shared_preferences: ^2.0.13
  internet_connection_checker: ^0.0.1+3
  url_launcher: ^6.1.0
  google_mobile_ads: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_app.jpg"

  flutter_lints: ^1.0.0

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
